// This file is automatically generated by the command
// lua hardcode.lua appliedfield_heterogeneous_luafuncs.lua

extern "C"{
const char* __appliedfield_heterogeneous_luafuncs_name();
const char* __appliedfield_heterogeneous_luafuncs();
}
