#ifndef LUAGRAPHICS_QTGL_GLOBAL_H
#define LUAGRAPHICS_QTGL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LUAGRAPHICS_QTGL_LIBRARY)
#  define LUAGRAPHICS_QTGLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LUAGRAPHICS_QTGLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LUAGRAPHICS_QTGL_GLOBAL_H
