# Copyright (C) 2011 Jason Mercer.  All rights reserved.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

OBJECTS=libLuaGraphics.o Vector.o Matrix.o Sphere.o Ray.o \
	Volume.o Draw.o DrawPOVRay.o Color.o Light.o \
	Tube.o AABB.o Group.o Camera.o Plane.o Transformation.o \
	TransformationScale.o TransformationTranslate.o TransformationRotate.o
LIBNAME=LuaGraphics
CATEGORY=extra

#DEPEND is parsed to make the vs2010 project
DEPEND=luabaseobject
BASEDIR=../../..
include $(BASEDIR)/makefile.common.cpu


# OBJECTS=Vector.o Matrix.o Sphere.o Atom.o Ray.o UnitCell.o Triangle.o \
# 	Volume.o Tetrahedron.o VolumeLua.o Draw.o DrawPOVRay.o Color.o \
# 	Camera.o libLuaGraphics.o Light.o Tube.o AABB.o Plane.o Group.o
