filename = arg[1]

f = io.open(filename, "r")

if f == nil then
	error("failed to open `" .. filename .. "'")
end

a, b, base = string.find(filename, "(.*)\.lua")

if base == nil then
	error("filename must end with .lua")
end
	
bytes = {}
repeat
	c = f:read(1)
	if c ~= nil then
		local b = string.byte(c)
		table.insert(bytes, b)
	end
until c == nil

f:close()

f_cpp = io.open(base .. ".cpp", "w")

N = table.maxn(bytes)

f_cpp:write("// This file is automatically generated by the command\n")
f_cpp:write("// lua hardcode.lua " .. filename .. "\n\n")
f_cpp:write("#include \"" .. base .. ".h\"\n")

baseFixed = string.gsub(base, "%-", "")
baseFixed = string.gsub(baseFixed, "%.", "")
M = string.len(filename)

f_cpp:write("static char " .. baseFixed .. "_filename[" .. M+1 .. "] = \"" .. filename .. "\";\n")
f_cpp:write("static char " .. baseFixed .. "_chunkname[" .. M+2 .. "] = \"=" .. filename .. "\";\n")

f_cpp:write("// The following is the file " .. filename .. " encoded in hex\n")
f_cpp:write("static char " .. baseFixed .. "[" .. N+1 .. "] = {\n")

i = 0
while i <= N do
    for j=1,16 do
        i=i+1
        if i<=N then
            f_cpp:write(string.format("0x%02X,", bytes[i]))
            if j == 16 then
                f_cpp:write("\n")
            end
        end
    end
end
f_cpp:write(string.format("0x%02x};\n", 0))

f_cpp:write("const char* __" .. baseFixed .. "_filename() {return " .. baseFixed .. "_filename;}\n")
f_cpp:write("const char* __" .. baseFixed .. "_chunkname() {return " .. baseFixed .. "_chunkname;}\n")
f_cpp:write("const char* __" .. baseFixed .. "() {return " .. baseFixed .. ";}\n")


f_cpp:close()


f_h = io.open(base .. ".h", "w")
f_h:write("// This file is automatically generated by the command\n")
f_h:write("// lua hardcode.lua " .. filename .. "\n\n")

f_h:write("extern \"C\"{\n")
f_h:write("const char* __" .. baseFixed .. "_filename();\n")
f_h:write("const char* __" .. baseFixed .. "_chunkname();\n")
f_h:write("const char* __" .. baseFixed .. "();\n")

f_h:write("}\n\n")

f_h:write("// convenience macro\n")
f_h:write(string.format(
[[#define luaL_dofile_%s(L) \
{ \
  if(luaL_dostringn(L, __%s(), __%s_chunkname())) \
  { \
        fprintf(stderr, "%%s\n", lua_tostring(L, -1)); \
        return luaL_error(L, lua_tostring(L, -1)); \
  } \
}
]], baseFixed, baseFixed ,baseFixed))
f_h:close()