filename = arg[1]

f = io.open(filename, "r")

if f == nil then
	error("failed to open `" .. filename .. "'")
end

a, b, base = string.find(filename, "(.*)\.lua")

if base == nil then
	error("filename must end with .lua")
end
	
bytes = {}
repeat
	c = f:read(1)
	if c ~= nil then
		local b = string.byte(c)
		table.insert(bytes, b)
	end
until c == nil

f:close()

f = io.open(base .. ".h", "w")

N = table.maxn(bytes)

f:write("// This file is automatically generated by the command\n")
f:write("// lua hardcode.lua " .. filename .. "\n\n")
f:write("const char __" .. base .. "[" .. N+1 .. "] = {\n")

i = 0
while i <= N do
	for j=1,16 do
		i=i+1
		if i<=N then
			f:write(string.format("0x%02X,", bytes[i]))
			if j == 16 then
				f:write("\n")
			end
		end
	end
end
f:write(string.format("0x%02x};\n", 0))
f:close()
